### ISSUE TITLE
[PE-D] GUI for Lab tags

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F10-1/tp#105]
Maybe can add a space to the Lab tags similar to the regular tags, to help the GUI look better

![image.png](https://raw.githubusercontent.com/Justinnje/ped/main/files/6d978a25-5f3e-4429-b2b3-a12648c2d04f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Justinnje/ped#6

**Comment by bryans17** [comment]
Slightly related to #98. (Long lab numbers will cause this issue.)
