### ISSUE TITLE
[PE-D] Labsub

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F10-1/tp#109]
Able to input:
labadd l/3
labadd l/6
labsub 1 l/3 l/6

Ouput:
only lab 6 is marked as submitted

Undocumented in the User Guide.
does not impact the functionality of the application.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: tanyutao544/ped#4

**Comment by bryans17** [comment]
Related to #108.
